project_name: coincheadversarial

wandb: True
algorithm: DCFR #PPO
policy: MlpPolicy
env_id: coinche-v4
total_timesteps: 10 #1_000_000

log_every: 1                 # Log every episode
checkpoint_every: 1000 #10_000       # Save model every N steps
eval_every: 1000 #10_000             # (Optional) evaluate agent every N steps


gradient_save_freq: 0         # (Optional) save gradient every N steps (0 is never)

log_game_metrics: true      # Log contract, suit, etc.
save_game_replays: true     # Save replays for analysis

num_envs: 8
n_steps: 512
batch_size: 256
n_epochs: 10

'cfr_players': "self_play" 

# "self_play" = [GymPlayer, GymPlayer, GymPlayer, GymPlayer]
# "det_opponent" = [GymPlayer, DeterministicPlayer, GymPlayer, DeterministicPlayer]
# "random_opponent" = [GymPlayer, RandomPlayer, GymPlayer, RandomPlayer]
# 'det2_opponent' =  [GymPlayer, DeterministicPlayer_v2, DeterministicPlayer_v2, DeterministicPlayer_v2]