project_name: coincheadversarial
algorithm: PPO
env_id: coinche-v3
total_timesteps: 10000

log_every: 1                 # Log every episode
checkpoint_every: 10000       # Save model every N steps
eval_every: 10000             # (Optional) evaluate agent every N steps
gradient_save_freq: 0         # (Optional) save gradient every N steps (0 is never)

log_game_metrics: true       # Log contract, suit, etc.
save_game_replays: true      # Save replays for analysis

num_envs: 8
n_steps: 2048
batch_size: 4096
policy: MultiInputPolicy